---
title: '20200526'
author: "Cindy"
date: "2020/5/26"
output: html_document
---
## On list

```{r}
library(purrr)
```

###  每個元素相同運算




```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```
</div>我們有可能想要拿出其中屬於小新的資料:

```{r}
names(example)
```


```{r}
pick_小新 <- example$name == "小新"
data_selected <-
  list(
    name=example$name[pick_小新],
    weight=example$weight[pick_小新],
    height=example$height[pick_小新],
    hobby=example$hobby[pick_小新],
    residence=example$residence[pick_小新],
    allowance=example$allowance[pick_小新],
    bloodType=example$bloodType[pick_小新]
  )
```















































  * 對`example` 底下的每個元素進行
  
  * `.x[pick_小新]` 的動作
  












```{r, eval=TRUE, message=FALSE, echo=F}
jsonlite::fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
jsonlite::fromJSON("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3", simplifyDataFrame = F) -> dance
```


```{r}
str(dance)
```















```{r}
map(dance,~.x$title) -> 
  list_titles

View(list_titles)
```

每個表演不只演出一場,每個表演的場次總數:
```{r}
#記載第一個表演的所有場次訊息
dance[[1]]$showInfo
str(dance[[1]]$showInfo)
#計算第一個表演有幾個場次
length(dance[[1]]$showInfo)
#計算第二個表演有幾個場次
length(dance[[2]]$showInfo)
```



  * `length(.x$showInfo)`的動作
  
```{r}
map(dance,~length(.x$showInfo)) -> 
  list_numberOfShows

View(list_numberOfShows)
```

第5個表演有4個場次,想知道他們的日期時間:

```{r}
str(dance[[5]]$showInfo)
```























```{r, eval=F, echo=F}
dance[[8]]$showInfo[[1]][c("time","location")]

list_dance8_timeLocations <- map(dance[[8]]$showInfo,~.x[c("time","location")])

print(list_dance8_timeLocations)
```
</div>


```{r}
num <- c(2,5,7,1,3)
num[[1]]+3
num[[2]]+3
num[[4]]+3
```

```{r}
map(num, ~ .x+3)
```